# Generated by Django 2.0.4 on 2018-05-10 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=256)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.TimeField(blank=True, default=datetime.datetime(2018, 5, 10, 4, 0))),
                ('fecha_efectiva', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, default=datetime.datetime.today)),
                ('hora_inicio', models.TimeField(blank=True, default=datetime.time(10, 0))),
                ('hora_final', models.TimeField(blank=True, default=datetime.time(12, 0))),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
            ],
            options={
                'verbose_name': 'Exposición',
                'verbose_name_plural': 'Exposiciones',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=254)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(blank=True, choices=[('a', 'activo'), ('i', 'inactivo')], default='a', max_length=1)),
                ('fecha', models.DateField(default=datetime.datetime.today, editable=False)),
            ],
            options={
                'verbose_name': 'Expositor',
                'verbose_name_plural': 'Expositores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=120)),
                ('salon', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['direccion'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_estudio', models.TextField(max_length=80)),
                ('guia_estudio', models.TextField(max_length=80)),
                ('multi_medios', models.CharField(blank=True, choices=[('d', 'DVD'), ('c', 'CD'), ('u', 'USB'), ('k', 'Disco'), ('o', 'Otro')], default='o', max_length=1)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['evento'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Entre su cedula', max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha', models.DateField(default=datetime.datetime.today, editable=False)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.today)),
                ('fecha_fin', models.DateField(default=datetime.datetime.today)),
                ('imagen', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
                ('nombre_ciclo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Ciclo')),
                ('nombre_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Programa')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.today, editable=False)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
                ('exposicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Exposicion')),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Participante')),
            ],
            options={
                'ordering': ['evento', 'participante'],
            },
        ),
        migrations.AddField(
            model_name='exposicion',
            name='expositor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Expositor'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Localidad'),
        ),
    ]
