# Generated by Django 2.0.4 on 2018-05-10 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_efectiva',
            field=models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0), editable=False),
        ),
    ]
