# Generated by Django 2.0.4 on 2018-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20180510_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='guia_estudio',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='material',
            name='libro_estudio',
            field=models.CharField(max_length=80),
        ),
    ]
