# Generated by Django 2.0.4 on 2018-05-10 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20180510_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cedula',
            field=models.CharField(blank=True, help_text='Entre su cedula', max_length=11, null=True, validators=[django.core.validators.RegexValidator('\\d', 'Solo numeros son permitidos')]),
        ),
    ]
