# Generated by Django 2.0.4 on 2018-05-10 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20180510_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
