# Generated by Django 2.0.4 on 2018-05-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_ciclo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='estado',
        ),
    ]
