# Generated by Django 2.0.4 on 2018-05-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_remove_ciclo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['nombre', 'direccion'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
    ]
