# Generated by Django 2.0.4 on 2018-05-15 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20180514_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(blank=True, choices=[('a', 'activo'), ('i', 'inactivo')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 5, 15, 4, 0)),
        ),
    ]
