# Generated by Django 2.0.4 on 2018-05-15 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20180515_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='evento',
            name='nota',
            field=models.CharField(blank=True, help_text='Entre una nota breve', max_length=60),
        ),
    ]
