# Generated by Django 2.0.5 on 2018-06-24 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_auto_20180515_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['evento']},
        ),
        migrations.RemoveField(
            model_name='registro',
            name='participante',
        ),
        migrations.AddField(
            model_name='registro',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='cedula',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 6, 24, 4, 0)),
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
